/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminBreadcrumb: typeof import('./src/components/layout/AdminBreadcrumb.vue')['default']
    AdminHeader: typeof import('./src/components/layout/AdminHeader.vue')['default']
    AdminHome: typeof import('./src/components/home/AdminHome.vue')['default']
    AdminMenu: typeof import('./src/components/layout/AdminMenu.vue')['default']
    AdminOverview: typeof import('./src/components/home/adminHome/AdminOverview.vue')['default']
    BarChart: typeof import('./src/components/home/adminHome/BarChart.vue')['default']
    BookInfo: typeof import('./src/components/books/BookInfo.vue')['default']
    BookManagement: typeof import('./src/components/books/BookManagement.vue')['default']
    BookSearch: typeof import('./src/components/books/BookSearch.vue')['default']
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    copy: typeof import('./src/components/books/BookManagement copy.vue')['default']
    DatavManagement: typeof import('./src/components/datav/DatavManagement.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HistoryManagement: typeof import('./src/components/history/HistoryManagement.vue')['default']
    LineChart: typeof import('./src/components/home/adminHome/LineChart.vue')['default']
    PieChart: typeof import('./src/components/home/adminHome/PieChart.vue')['default']
    RecommendManagement: typeof import('./src/components/recommend/RecommendManagement.vue')['default']
    RecommendManagementOrigin: typeof import('./src/components/recommend/RecommendManagementOrigin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarRatings: typeof import('./src/components/books/bookinfo/StarRatings.vue')['default']
    TemplateView: typeof import('./src/components/books/bookinfo/TemplateView.vue')['default']
    UsersManagement: typeof import('./src/components/users/UsersManagement.vue')['default']
  }
}
