from extension import db

class BookTest(db.Model):
    __tablename__ = 'data_test'
    collection_time = db.Column(db.String(255), primary_key=True)
    Image_address = db.Column(db.String(255))
    book_link = db.Column(db.String(255))
    book_title = db.Column(db.String(255))
    book_subtitle = db.Column(db.String(255))
    book_id = db.Column(db.String(255))
    author = db.Column(db.String(255))
    press = db.Column(db.String(255))
    original_title = db.Column(db.String(255))
    translator = db.Column(db.String(255))
    translator_introduction = db.Column(db.String(255))
    publication_year = db.Column(db.String(255))
    pages = db.Column(db.String(255))
    price = db.Column(db.String(255))
    binding = db.Column(db.String(255))
    ISBN = db.Column(db.String(255))
    series = db.Column(db.String(255))
    series_link = db.Column(db.String(255))
    rating = db.Column(db.String(255))
    rating_number = db.Column(db.String(255))
    content_validity = db.Column(db.String(255))
    author_introduction = db.Column(db.String(255))
    menu = db.Column(db.String(255))
    label = db.Column(db.String(255))